# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 456)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(513, 456))
        MainWindow.setMaximumSize(QtCore.QSize(513, 456))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Info_label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Info_label_1.setGeometry(QtCore.QRect(130, 0, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Info_label_1.setFont(font)
        self.Info_label_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Info_label_1.setObjectName("Info_label_1")
        self.Info_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Info_label_2.setGeometry(QtCore.QRect(20, 80, 101, 51))
        self.Info_label_2.setObjectName("Info_label_2")
        self.Info_label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Info_label_3.setGeometry(QtCore.QRect(150, 80, 101, 51))
        self.Info_label_3.setObjectName("Info_label_3")
        self.Info_label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Info_label_4.setGeometry(QtCore.QRect(280, 80, 121, 51))
        self.Info_label_4.setObjectName("Info_label_4")
        self.Info_label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Info_label_5.setGeometry(QtCore.QRect(410, 80, 121, 51))
        self.Info_label_5.setObjectName("Info_label_5")
        self.Open_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Open_button.setGeometry(QtCore.QRect(410, 350, 75, 41))
        self.Open_button.setObjectName("Open_button")
        self.File_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.File_input.setGeometry(QtCore.QRect(280, 360, 113, 20))
        self.File_input.setObjectName("File_input")
        self.Info_display = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.Info_display.setGeometry(QtCore.QRect(10, 190, 256, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Info_display.sizePolicy().hasHeightForWidth())
        self.Info_display.setSizePolicy(sizePolicy)
        self.Info_display.setMinimumSize(QtCore.QSize(256, 192))
        self.Info_display.setMaximumSize(QtCore.QSize(256, 192))
        self.Info_display.setObjectName("Info_display")
        self.Low_grade = QtWidgets.QLabel(parent=self.centralwidget)
        self.Low_grade.setGeometry(QtCore.QRect(30, 130, 47, 13))
        self.Low_grade.setObjectName("Low_grade")
        self.High_grade = QtWidgets.QLabel(parent=self.centralwidget)
        self.High_grade.setGeometry(QtCore.QRect(170, 130, 47, 13))
        self.High_grade.setObjectName("High_grade")
        self.Students_amount = QtWidgets.QLabel(parent=self.centralwidget)
        self.Students_amount.setGeometry(QtCore.QRect(430, 130, 47, 13))
        self.Students_amount.setObjectName("Students_amount")
        self.Average_grade = QtWidgets.QLabel(parent=self.centralwidget)
        self.Average_grade.setGeometry(QtCore.QRect(290, 130, 47, 13))
        self.Average_grade.setObjectName("Average_grade")
        self.Entry_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Entry_label.setGeometry(QtCore.QRect(310, 340, 61, 16))
        self.Entry_label.setObjectName("Entry_label")
        self.Close_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Close_Button.setGeometry(QtCore.QRect(410, 390, 75, 23))
        self.Close_Button.setObjectName("Close_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 513, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Info_label_1.setText(_translate("MainWindow", "Class"))
        self.Info_label_2.setText(_translate("MainWindow", "Lowest Grade"))
        self.Info_label_3.setText(_translate("MainWindow", "Highest Grade"))
        self.Info_label_4.setText(_translate("MainWindow", "Grade Average"))
        self.Info_label_5.setText(_translate("MainWindow", "Students in Class"))
        self.Open_button.setText(_translate("MainWindow", "Open"))
        self.Info_display.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please enter the csv file you would like to open (don\'t include &quot;.csv&quot; at the end)</p></body></html>"))
        self.Low_grade.setText(_translate("MainWindow", "0000"))
        self.High_grade.setText(_translate("MainWindow", "0000"))
        self.Students_amount.setText(_translate("MainWindow", "0000"))
        self.Average_grade.setText(_translate("MainWindow", "0000"))
        self.Entry_label.setText(_translate("MainWindow", "File Name"))
        self.Close_Button.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
